/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.rastak.git;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.apache.commons.lang.StringUtils;

/**
 *
 * @author r.rastakfard
 */
public class TstPanel extends javax.swing.JPanel {

    GetAffectedFilesInCommitForm parent;
    /**
     * Creates new form TstPanel
     */
    public TstPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        generateDiffBtn = new javax.swing.JButton();
        authorNameForDiff = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fromCommitIdInp = new javax.swing.JTextField();
        toCommitIdInp = new javax.swing.JTextField();
        clearCreateDiffPatchPanelBtn = new javax.swing.JButton();
        getDiffToHead = new javax.swing.JButton();
        viewLastDiffBtn = new javax.swing.JButton();

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel7.setText("Author Name Like");

        generateDiffBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        generateDiffBtn.setText("Generate Diff Patch");
        generateDiffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateDiffBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("From Commit ID");

        jLabel9.setText("To Commit ID");

        clearCreateDiffPatchPanelBtn.setText("Clear Panel");
        clearCreateDiffPatchPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearCreateDiffPatchPanelBtnActionPerformed(evt);
            }
        });

        getDiffToHead.setText("Get DIFF TO HEAD");
        getDiffToHead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getDiffToHeadActionPerformed(evt);
            }
        });

        viewLastDiffBtn.setText("View Last Diff");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(authorNameForDiff, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                            .addComponent(fromCommitIdInp)
                            .addComponent(toCommitIdInp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(generateDiffBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(getDiffToHead, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(viewLastDiffBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(clearCreateDiffPatchPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(authorNameForDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateDiffBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fromCommitIdInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewLastDiffBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(toCommitIdInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getDiffToHead))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearCreateDiffPatchPanelBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 849, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(83, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void generateDiffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateDiffBtnActionPerformed
        if (parent.fillBaseProjectPath() == null) {
            return;
        }
        if (StringUtils.isEmpty(fromCommitIdInp.getText())){
            JOptionPane.showMessageDialog(this, "Please Select From Commit ID.");
            return;
        }
        if (StringUtils.isEmpty(toCommitIdInp.getText())) {
            JOptionPane.showMessageDialog(this, "Please Select To Commit ID.");
            return;
        }
        String changedFiles = "";//TODO changedListFilesTxt.getText();
        if (!StringUtils.isEmpty(changedFiles)) {
            String[] splitedChangedFiles = changedFiles.split("\n");
            for (String changedFilePath : splitedChangedFiles) {
                if (!StringUtils.isEmpty(changedFilePath)) {
                    List<String> diffCommand = new ArrayList<String>();
                    diffCommand.add("git");
                    diffCommand.add("diff");
                    diffCommand.add("--diff-algorithm=patience");
                    //                    diffCommand.add("--find-copies-harder");
                    //                    diffCommand.add("-B");
                    //                    diffCommand.add("-C");
                    diffCommand.add(fromCommitIdInp.getText().trim()+"~1.."+toCommitIdInp.getText().trim());
                    diffCommand.add("--");
                    diffCommand.add(changedFilePath);
                    String diffCommandResult = parent.processCommand(parent.fillBaseProjectPath(), diffCommand);
                    System.out.println(diffCommandResult);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No files selected to generate diff.");
        }
    }//GEN-LAST:event_generateDiffBtnActionPerformed

    private void clearCreateDiffPatchPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearCreateDiffPatchPanelBtnActionPerformed
        fromCommitIdInp.setText("");
        toCommitIdInp.setText("");
        authorNameForDiff.setText("");
    }//GEN-LAST:event_clearCreateDiffPatchPanelBtnActionPerformed

    private void getDiffToHeadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getDiffToHeadActionPerformed
        toCommitIdInp.setText("HEAD");
    }//GEN-LAST:event_getDiffToHeadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authorNameForDiff;
    private javax.swing.JButton clearCreateDiffPatchPanelBtn;
    private javax.swing.JTextField fromCommitIdInp;
    private javax.swing.JButton generateDiffBtn;
    private javax.swing.JButton getDiffToHead;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField toCommitIdInp;
    private javax.swing.JButton viewLastDiffBtn;
    // End of variables declaration//GEN-END:variables
}
